- hosts: all
  become: true
  tasks:
    - name: Install packages that allow apt to be used over HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add apt repository for stable version
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: Install docker and its dependecies
      apt: 
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce 
        - docker-ce-cli 
        - containerd.io
      notify:
        - docker status

    - name: Install python and relative modules
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - python-pip
          - python-setuptools

    - name: Install python docker module
      pip:
        name: docker
      become: yes
      become_method: sudo

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        group: docker

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none

    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: Create certificates directory
      file:
        path: certs
        state: directory

    - name: Generate self-signed certificate
      command: openssl req -newkey rsa:4096 -nodes -sha256 -keyout certs/domain.key -x509 -days 365 -out certs/domain.crt -subj '/CN=registrydomain.com'
      become: yes
      become_method: sudo

    - name: Copy certificates on the control machine
      fetch:
        src: /home/vagrant/certs/domain.crt
        dest: ./ca.crt
        flat: yes

    - name: Add registry domain to hosts file
      lineinfile:
        path: /etc/hosts
        line: 127.0.0.1 registrydomain.com
        create: yes

    - name: Start docker registry
      docker_container:
        name: registry
        image: registry:2
        state: started
        published_ports: 443:443
        volumes:
          - /home/vagrant/certs:/certs
        restart_policy: always
        env:
          REGISTRY_HTTP_ADDR: "0.0.0.0:443"
          REGISTRY_HTTP_TLS_CERTIFICATE: "/certs/domain.crt"
          REGISTRY_HTTP_TLS_KEY: "/certs/domain.key"

  handlers:
    - name: docker status
      service: name=docker state=started